// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2Parcial_BonillaAp1.Server.DAL;

#nullable disable

namespace _2Parcial_BonillaAp1.Server.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230711194220_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("_2Parcial_BonillaAp1.Shared.Models.Entradas", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadProducida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("PesoTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("_2Parcial_BonillaAp1.Shared.Models.EntradasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadUtilizada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Disponibilidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrutoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("_2Parcial_BonillaAp1.Shared.Models.Frutos", b =>
                {
                    b.Property<int>("FrutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Disponibilidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("FrutoId");

                    b.ToTable("Frutos");

                    b.HasData(
                        new
                        {
                            FrutoId = 1,
                            Disponibilidad = 100,
                            Nombre = "Mani"
                        },
                        new
                        {
                            FrutoId = 2,
                            Disponibilidad = 100,
                            Nombre = "Pasas"
                        },
                        new
                        {
                            FrutoId = 3,
                            Disponibilidad = 100,
                            Nombre = "Pistacho"
                        },
                        new
                        {
                            FrutoId = 4,
                            Disponibilidad = 100,
                            Nombre = "Ciruela"
                        },
                        new
                        {
                            FrutoId = 5,
                            Disponibilidad = 100,
                            Nombre = "Arandanos"
                        });
                });

            modelBuilder.Entity("_2Parcial_BonillaAp1.Shared.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Peso")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("_2Parcial_BonillaAp1.Shared.Models.EntradasDetalle", b =>
                {
                    b.HasOne("_2Parcial_BonillaAp1.Shared.Models.Entradas", null)
                        .WithMany("EntradasDetalles")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2Parcial_BonillaAp1.Shared.Models.Entradas", b =>
                {
                    b.Navigation("EntradasDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
